Repository cable8mm/xeed, pull requests merged in 2024-03, with the labels that each got.

#1 Resolve badge errors in the README
  README.md
Labels: bug

#2 Build in sqlite for testing
  .env.example
  .github/workflows/run-tests.yml
  .gitignore
  README.md
  composer.json
  database/Seeder.php
  phpunit.xml.dist
  src/Column.php
  src/DB.php
  src/Example.php
  src/Interfaces/Provider.php
  src/Provider/MysqlProvider.php
  src/Provider/SqliteProvider.php
  src/Table.php
  tests/DBTest.php
  tests/ExampleTest.php
  tests/PhpunitTest.php
  tests/SeederTest.php
Labels: enhancement

#5 Revise the folder structure for distribution
  dist/app/Models/.gitignore
  dist/database/factories/.gitignore
  dist/database/migrations/.gitignore
  dist/database/seeders/.gitignore
  src/Generators/ModelGenerator.php
  src/Generators/SeederGenerator.php
  src/Path.php
  src/Traits/SeederGeneratorMakable.php
  tests/Unit/ModelGeneratorTest.php
  tests/Unit/SeederGeneratorTest.php
Labels: enhancement

#8 Add Comments to Classes for API Documentation
  .gitignore
  composer.json
  src/Column.php
  src/DB.php
  src/Generators/DatabaseSeederGenerator.php
  src/Generators/ModelGenerator.php
  src/Generators/SeederGenerator.php
  src/Interfaces/Generator.php
  src/Interfaces/Provider.php
  src/Provider/MysqlProvider.php
  src/Provider/SqliteProvider.php
  src/Resolvers/Resolver.php
  src/Support/Path.php
  src/Table.php
Labels: documentation

#9 Generate models command creation
  README.md
  bin/console
  composer.json
  src/Command/GenerateModelsCommand.php
  src/Generators/ModelGenerator.php
  src/Support/Inflector.php
Labels: enhancement

#10 Generate `seeder`s command creation
  bin/console
  database/seeders/.gitignore
  src/Command/GenerateSeedersCommand.php
  src/Generators/SeederGenerator.php
Labels: enhancement

#11 Generate database seed command creation
  README.md
  bin/console
  src/Command/GenerateDatabaseSeederCommand.php
Labels: enhancement

#12 Provide API Documentation on the Web
  .github/workflows/deploy-to-github-pages.yml
  README.md
  composer.json
Labels: documentation

#13 Align test folder structure with source folder
  resources/tests/2024_03_15_034619_create_xeeds_table.php.test
  resources/tests/xeeds.sql.test
  tests/Feature/PhpunitTest.php
  tests/Unit/DBTest.php
  tests/Unit/Generators/DatabaseSeederGeneratorTest.php
  tests/Unit/Generators/ModelGeneratorTest.php
  tests/Unit/Generators/SeederGeneratorTest.php
  tests/Unit/SeederGeneratorTest.php
  tests/Unit/SeederTest.php
Labels: documentation

#14 Create import xeed command for testing
  bin/console
  resources/tests/xeeds.sql
  src/Command/ImportXeedCommand.php
  src/Support/Inflector.php
  src/Support/Path.php
  tests/Unit/Generators/ModelGeneratorTest.php
  tests/Unit/Generators/SeederGeneratorTest.php
Labels: enhancement

#15 Implementing a year type factory
  .github/workflows/run-tests.yml
  .gitignore
  README.md
  database/Seeder.php
  docs/LARAVEL_MIGRATIONS.md
  phpunit.xml.dist
  resources/tests/xeeds.mysql.sql
  resources/tests/xeeds.sqlite.sql
  src/Command/ImportXeedCommand.php
  src/DB.php
  src/Mappers/mysql.php
  src/Mappers/sqlite.php
  src/Provider/SqliteProvider.php
  src/Resolvers/Resolver.php
  src/Resolvers/YearResolver.php
  src/Support/Path.php
  src/Support/Picker.php
  tests/Unit/DBTest.php
  tests/Unit/Resolvers/YearResolverTest.php
Labels: enhancement

#16 Expand test coverage significantly for Resolvers and enhance their functionality
  composer.json
  src/Column.php
  src/Interfaces/Provider.php
  src/Provider/MysqlProvider.php
  src/Provider/SqliteProvider.php
  src/Resolvers/CharResolver.php
  src/Resolvers/DoubleResolver.php
  src/Resolvers/FloatResolver.php
  src/Resolvers/Resolver.php
  src/Support/Picker.php
  tests/Unit/Resolvers/BigintResolverTest.php
  tests/Unit/Resolvers/BoolResolverTest.php
  tests/Unit/Resolvers/BooleanResolverTest.php
  tests/Unit/Resolvers/CharResolverTest.php
  tests/Unit/Resolvers/DateResolverTest.php
  tests/Unit/Resolvers/DatetimeResolverTest.php
  tests/Unit/Resolvers/DoubleResolverTest.php
  tests/Unit/Resolvers/FloatResolverTest.php
  tests/Unit/Resolvers/IntResolverTest.php
  tests/Unit/Resolvers/IntegerResolverTest.php
  tests/Unit/Resolvers/TextResolverTest.php
  tests/Unit/Resolvers/VarcharResolverTest.php
  tests/Unit/Resolvers/YearResolverTest.php
  tests/Unit/Support/PickerTest.php
Labels: enhancement

#18 Fix an error related to default values
  src/Resolvers/Resolver.php
  tests/Unit/Resolvers/BigintResolverTest.php
  tests/Unit/Resolvers/BoolResolverTest.php
  tests/Unit/Resolvers/BooleanResolverTest.php
  tests/Unit/Resolvers/CharResolverTest.php
  tests/Unit/Resolvers/DateResolverTest.php
  tests/Unit/Resolvers/DatetimeResolverTest.php
  tests/Unit/Resolvers/DecimalResolverTest.php
  tests/Unit/Resolvers/DoubleResolverTest.php
  tests/Unit/Resolvers/FloatResolverTest.php
  tests/Unit/Resolvers/IntResolverTest.php
  tests/Unit/Resolvers/IntegerResolverTest.php
  tests/Unit/Resolvers/JsonResolverTest.php
  tests/Unit/Resolvers/LongtextResolverTest.php
  tests/Unit/Resolvers/MacaddressResolverTest.php
  tests/Unit/Resolvers/MediumintResolverTest.php
  tests/Unit/Resolvers/MediumtextResolverTest.php
  tests/Unit/Resolvers/RemembertokenResolverTest.php
  tests/Unit/Resolvers/SmallintResolverTest.php
  tests/Unit/Resolvers/StringResolverTest.php
  tests/Unit/Resolvers/TextResolverTest.php
  tests/Unit/Resolvers/TimeResolverTest.php
  tests/Unit/Resolvers/TimestampResolverTest.php
  tests/Unit/Resolvers/TinyintResolverTest.php
  tests/Unit/Resolvers/TinytextResolverTest.php
  tests/Unit/Resolvers/UnsignedBigIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedDecimalResolverTest.php
  tests/Unit/Resolvers/UnsignedIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedMediumIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedSmallIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedTinyIntegerResolverTest.php
  tests/Unit/Resolvers/VarcharResolverTest.php
  tests/Unit/Resolvers/YearResolverTest.php
Labels: bug

#19 Test code compatible with MySQL
  src/Provider/MysqlProvider.php
  src/Resolvers/BigintResolver.php
  src/Resolvers/DecimalResolver.php
  src/Resolvers/IntResolver.php
  src/Resolvers/SmallintResolver.php
  src/Resolvers/TinyintResolver.php
  tests/Feature/PhpunitTest.php
  tests/Unit/Resolvers/BigintResolverTest.php
  tests/Unit/Resolvers/DecimalResolverTest.php
  tests/Unit/Resolvers/IntResolverTest.php
  tests/Unit/Resolvers/IntegerResolverTest.php
  tests/Unit/Resolvers/SmallintResolverTest.php
  tests/Unit/Resolvers/TinyintResolverTest.php
  tests/Unit/Resolvers/UnsignedIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedMediumIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedSmallIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedTinyIntegerResolverTest.php
Labels: enhancement

#23 Add a command for easy testing refresh
  src/Command/ImportXeedCommand.php
  tests/Unit/Command/ImportXeedCommandTest.php
Labels: enhancement

#24 Refactor to remove an abstract class
  composer.json
  src/Column.php
  src/Interfaces/ResolverInterface.php
  src/Resolvers/BigintResolver.php
  src/Resolvers/BinaryResolver.php
  src/Resolvers/BitResolver.php
  src/Resolvers/BlobResolver.php
  src/Resolvers/BoolResolver.php
  src/Resolvers/CharResolver.php
  src/Resolvers/DateResolver.php
  src/Resolvers/DatetimeResolver.php
  src/Resolvers/DecimalResolver.php
  src/Resolvers/DoubleResolver.php
  src/Resolvers/EnumResolver.php
  src/Resolvers/FloatResolver.php
  src/Resolvers/GeometryResolver.php
  src/Resolvers/GeometrycollectionResolver.php
  src/Resolvers/IdResolver.php
  src/Resolvers/InetResolver.php
  src/Resolvers/IntResolver.php
  src/Resolvers/JsonResolver.php
  src/Resolvers/JsonbResolver.php
  src/Resolvers/LineStringResolver.php
  src/Resolvers/LongblobResolver.php
  src/Resolvers/LongtextResolver.php
  src/Resolvers/MacaddressResolver.php
  src/Resolvers/MediumblobResolver.php
  src/Resolvers/MediumintResolver.php
  src/Resolvers/MediumtextResolver.php
  src/Resolvers/MorphsResolver.php
  src/Resolvers/MultipointResolver.php
  src/Resolvers/MultipolygonResolver.php
  src/Resolvers/PointResolver.php
  src/Resolvers/PolygonResolver.php
  src/Resolvers/RemembertokenResolver.php
  src/Resolvers/Resolver.php
  src/Resolvers/SetResolver.php
  src/Resolvers/SmallintResolver.php
  src/Resolvers/TextResolver.php
  src/Resolvers/TimeResolver.php
  src/Resolvers/TimestampResolver.php
  src/Resolvers/TinyblobResolver.php
  src/Resolvers/TinyintResolver.php
  src/Resolvers/TinytextResolver.php
  src/Resolvers/UlidResolver.php
  src/Resolvers/UlidmorphsResolver.php
  src/Resolvers/UuidResolver.php
  src/Resolvers/UuidmorphsResolver.php
  src/Resolvers/VarbinaryResolver.php
  src/Resolvers/VarcharResolver.php
  src/Resolvers/YearResolver.php
  src/Table.php
Labels: enhancement

#25 Debug the function to make migrations
  README.md
  src/Provider/MysqlProvider.php
  src/Resolvers/DecimalResolver.php
  src/Resolvers/DoubleResolver.php
  src/Resolvers/EnumResolver.php
  src/Resolvers/FloatResolver.php
  src/Resolvers/MediumintResolver.php
  src/Resolvers/RemembertokenResolver.php
  src/Resolvers/SetResolver.php
  src/Resolvers/TimeResolver.php
  src/Resolvers/TimestampResolver.php
  src/Resolvers/VarcharResolver.php
  src/Types/Bracket.php
  tests/Unit/Resolvers/BigintResolverTest.php
  tests/Unit/Resolvers/DecimalResolverTest.php
  tests/Unit/Resolvers/IntResolverTest.php
  tests/Unit/Resolvers/IntegerResolverTest.php
  tests/Unit/Resolvers/RemembertokenResolverTest.php
  tests/Unit/Resolvers/SmallintResolverTest.php
  tests/Unit/Resolvers/StringResolverTest.php
  tests/Unit/Resolvers/TimeResolverTest.php
  tests/Unit/Resolvers/TimestampResolverTest.php
  tests/Unit/Resolvers/TinyintResolverTest.php
  tests/Unit/Resolvers/UnsignedIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedMediumIntegerResolverTest.php
  tests/Unit/Resolvers/VarcharResolverTest.php
  tests/Unit/Types/BracketTest.php
Labels: bug, enhancement

#26 Debug the functions to make factories
  README.md
  resources/tests/2024_03_15_034619_create_xeeds_table.php.test
  resources/tests/xeeds.mysql.sql
  resources/tests/xeeds.sqlite.sql
  src/Generators/SeederGenerator.php
  src/ResolverSelector.php
  src/Resolvers/DecimalResolver.php
  src/Resolvers/EnumResolver.php
  src/Resolvers/GeometrycollectionResolver.php
  src/Resolvers/LineStringResolver.php
  src/Resolvers/MultipolygonResolver.php
  src/Resolvers/PointResolver.php
  src/Resolvers/PolygonResolver.php
  src/Resolvers/SetResolver.php
  src/Table.php
  tests/Unit/Command/GenerateSeedersCommandTest.php
  tests/Unit/Resolvers/MultipointResolverTest.php
  tests/Unit/Resolvers/MultipolygonResolverTest.php
  tests/Unit/Resolvers/PointResolverTest.php
  tests/Unit/Resolvers/PolygonResolverTest.php
  tests/Unit/Resolvers/UnsignedDecimalResolverTest.php
  tests/Unit/Resolvers/YearResolverTest.php
  tests/Unit/Types/BracketTest.php
Labels: enhancement

#27 Remove mappers that are slated to be unused
  src/Mappers/mysql.php
  src/Mappers/sqlite.php
  src/Support/Path.php
  src/Support/Picker.php
Labels: enhancement

#30 Refactor test classes and test configuration
  database/seeders/.gitignore
  phpunit.xml.dist
  tests/Feature/RetrieveTest.php
  tests/Seeder.php
  tests/Unit/DBTest.php
Labels: enhancement

#31 Support laravel custom table fields
  database/xeeds.mysql.sql
  database/xeeds.sqlite.sql
  src/Resolvers/BigintResolver.php
  src/Resolvers/DatetimeResolver.php
  src/Resolvers/TimestampResolver.php
  src/Resolvers/UlidResolver.php
  src/Resolvers/UuidResolver.php
Labels: enhancement

#32 Ready for merging to align with Laravel migration methods
  composer.json
  src/Interfaces/MergerInterface.php
  src/Mergers/Merger.php
  src/Mergers/MergerContainer.php
  src/Mergers/MorphsMerger.php
  src/Mergers/NullableMorphsMerger.php
  src/Mergers/NullableUlidMorphsMerger.php
  src/Mergers/NullableUuidMorphsMerger.php
  src/Mergers/TimestampsMerger.php
  src/Mergers/UlidMorphsMerger.php
  src/Mergers/UuidMorphsMerger.php
  src/ResolverSelector.php
  src/Support/Path.php
  tests/Bootstrap/Seeder.php
  tests/Bootstrap/migration.php.sample
  tests/Feature/RetrieveTest.php
  tests/Unit/DBTest.php
  tests/Unit/Mergers/MergerContainerTest.php
  tests/Unit/Mergers/MergerTest.php
  tests/Unit/Mergers/MorphsMergerTest.php
  tests/Unit/Mergers/NullableMorphsMergerTest.php
  tests/Unit/Mergers/NullableUlidMorphsMergerTest.php
  tests/Unit/Mergers/NullableUuidMorphsMergerTest.php
  tests/Unit/Mergers/TimestampsMergerTest.php
  tests/Unit/Mergers/UlidMorphsMergerTest.php
  tests/Unit/Mergers/UuidMorphsMergerTest.php
  tests/Unit/Types/BracketTest.php
Labels: enhancement

#33 Fix `MergerContainer` class bugs
  src/Mergers/Merger.php
  src/Mergers/MergerContainer.php
  tests/Feature/PostProcessTest.php
  tests/Unit/Mergers/MergerContainerTest.php
Labels: enhancement

#34 Refactor `Merger*` classes
  composer.json
  src/Mergers/Merger.php
  src/Mergers/MergerContainer.php
  src/Mergers/MorphsMerger.php
  src/Mergers/NullableMorphsMerger.php
  src/Mergers/NullableUlidMorphsMerger.php
  src/Mergers/NullableUuidMorphsMerger.php
  src/Mergers/TimestampsMerger.php
  src/Mergers/UlidMorphsMerger.php
  src/Mergers/UuidMorphsMerger.php
  src/Resolvers/Resolver.php
  src/Types/Bracket.php
  tests/Unit/Mergers/MergerTest.php
Labels: enhancement

#36 Add a README for Korean
  README.ko.md
  README.md
Labels: documentation

#37 Revise README file
  README.ko.md
  README.md
Labels: documentation

#38 Add a preview in the README file
  README.ko.md
  README.md
Labels: documentation

#39 Add the CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#42 Refactor class comments
  src/Column.php
  src/Generators/DatabaseSeederGenerator.php
  src/Generators/FactoryGenerator.php
  src/Generators/MigrationGenerator.php
  src/Generators/ModelGenerator.php
  src/Generators/SeederGenerator.php
  src/Interfaces/GeneratorInterface.php
  src/Interfaces/MergerInterface.php
  src/Interfaces/ProviderInterface.php
  src/Interfaces/ResolverInterface.php
  src/Mergers/Merger.php
  src/Mergers/MergerContainer.php
  src/ResolverSelector.php
  src/Resolvers/Resolver.php
  src/Support/File.php
  src/Support/Inflector.php
  src/Support/Path.php
  src/Support/Picker.php
  src/Table.php
  src/Types/Bracket.php
  src/Xeed.php
  tests/Unit/Mergers/MergerContainerTest.php
Labels: enhancement

#43 Set full namespace to class
  src/Generators/DatabaseSeederGenerator.php
  src/Generators/MigrationGenerator.php
  src/Interfaces/GeneratorInterface.php
  src/Mergers/MergerContainer.php
  src/Resolvers/Resolver.php
  src/Support/Picker.php
  src/Table.php
Labels: documentation

#44 Separate Xeed class and PDO
  src/Command/ImportXeedCommand.php
  src/Provider/MysqlProvider.php
  src/Provider/SqliteProvider.php
  src/Xeed.php
  tests/Bootstrap/Seeder.php
  tests/Unit/Command/ImportXeedCommandTest.php
  tests/Unit/XeedTest.php
Labels: enhancement

#46 Laravel Integration
  composer.json
  src/Laravel/XeedFacade.php
  src/Laravel/XeedServiceProvider.php
Labels: enhancement

#47 Add laravel artisan commands
  composer.json
  src/Command/CleanCommand.php
  src/Command/GenerateDatabaseSeederCommand.php
  src/Command/GenerateFactoriesCommand.php
  src/Command/GenerateMigrationsCommand.php
  src/Command/GenerateModelsCommand.php
  src/Command/GenerateSeedersCommand.php
  src/Command/ImportXeedCommand.php
  src/Generators/DatabaseSeederGenerator.php
  src/Generators/FactoryGenerator.php
  src/Generators/MigrationGenerator.php
  src/Generators/ModelGenerator.php
  src/Generators/SeederGenerator.php
  src/Laravel/Commands/GenerateDatabaseSeederCommand.php
  src/Laravel/Commands/GenerateFactoriesCommand.php
  src/Laravel/Commands/GenerateMigrationsCommand.php
  src/Laravel/Commands/GenerateModelsCommand.php
  src/Laravel/Commands/GenerateSeedersCommand.php
  src/Laravel/Commands/ImportXeedCommand.php
  src/Support/File.php
  src/Support/Path.php
  src/Xeed.php
  tests/Laravel/Commands/GenerateDatabaseSeederCommandTest.php
  tests/Laravel/Commands/GenerateFactoriesCommandTest.php
  tests/Laravel/Commands/GenerateMigrationsCommandTest.php
  tests/Laravel/Commands/GenerateModelsCommandTest.php
  tests/Laravel/Commands/GenerateSeedersCommandTest.php
  tests/Laravel/Commands/ImportXeedCommandTest.php
  tests/Unit/Command/GenerateSeedersCommandTest.php
  tests/Unit/Generators/DatabaseSeederGeneratorTest.php
  tests/Unit/Generators/FactoryGeneratorTest.php
  tests/Unit/Generators/MigrationGeneratorTest.php
  tests/Unit/Generators/ModelGeneratorTest.php
  tests/Unit/Generators/SeederGeneratorTest.php
  tests/Unit/Mergers/MergerContainerTest.php
Labels: enhancement

#48 Fix a `GenerateSeedersCommandTest`
  tests/Unit/Command/GenerateSeedersCommandTest.php
Labels: bug

#49 Address bugs found in the commands test
  src/Command/GenerateDatabaseSeederCommand.php
  src/Command/GenerateFactoriesCommand.php
  src/Command/GenerateMigrationsCommand.php
  src/Command/GenerateModelsCommand.php
  src/Command/GenerateSeedersCommand.php
  src/Command/ImportXeedCommand.php
  tests/Unit/Command/GenerateDatabaseSeederCommandTest.php
  tests/Unit/Command/GenerateFactoriesCommandTest.php
  tests/Unit/Command/GenerateMigrationsCommandTest.php
  tests/Unit/Command/GenerateModelsCommandTest.php
  tests/Unit/Command/GenerateSeedersCommandTest.php
Labels: bug

#50 Create the `artisan xeed:clean` command
  src/Laravel/Commands/CleanCommand.php
  src/Laravel/XeedServiceProvider.php
  tests/Laravel/Commands/CleanCommandTest.php
Labels: enhancement

#51 Fix errors and revise README
  README.md
  src/Xeed.php
  tests/Laravel/Commands/CleanCommandTest.php
Labels: bug, documentation

#52 Revise the Korean README
  README.ko.md
  README.md
Labels: documentation

#53 Fix a comment for Doctum
  src/Support/File.php
Labels: documentation

#54 Fix the install instructions(thank you hotsaucejake)
  README.ko.md
  README.md
Labels: bug, documentation

#55 Rename `laravel` to `for Laravel`
  README.ko.md
  README.md
Labels: documentation

#56 Include PostgreSQL driver
  README.ko.md
  README.md
  database/xeeds.pgsql.sql
  phpunit.xml.dist
  src/Command/GenerateDatabaseSeederCommand.php
  src/Command/GenerateFactoriesCommand.php
  src/Command/GenerateMigrationsCommand.php
  src/Command/GenerateModelsCommand.php
  src/Command/GenerateSeedersCommand.php
  src/Command/ImportXeedCommand.php
  src/Provider/PgsqlProvider.php
  src/ResolverSelector.php
  src/Resolvers/DateTimeTzResolver.php
  src/Resolvers/TimeTzResolver.php
  src/Resolvers/TimestampResolver.php
  src/Support/File.php
  src/Xeed.php
  tests/Bootstrap/0000_00_000000_create_xeeds_table.php
  tests/Bootstrap/Seeder.php
  tests/Unit/Command/ImportXeedCommandTest.php
  tests/Unit/Mergers/MergerContainerTest.php
  tests/Unit/Resolvers/BigintResolverTest.php
  tests/Unit/Resolvers/CharResolverTest.php
  tests/Unit/Resolvers/DecimalResolverTest.php
  tests/Unit/Resolvers/DoubleResolverTest.php
  tests/Unit/Resolvers/FloatResolverTest.php
  tests/Unit/Resolvers/IntResolverTest.php
  tests/Unit/Resolvers/IntegerResolverTest.php
  tests/Unit/Resolvers/SmallintResolverTest.php
  tests/Unit/Resolvers/StringResolverTest.php
  tests/Unit/Resolvers/TinyintResolverTest.php
  tests/Unit/Resolvers/UnsignedBigIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedMediumIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedSmallIntegerResolverTest.php
  tests/Unit/Resolvers/UnsignedTinyIntegerResolverTest.php
  tests/Unit/Resolvers/VarcharResolverTest.php
  tests/Unit/Resolvers/YearResolverTest.php
  tests/Unit/Support/FileTest.php
  tests/Unit/XeedTest.php
Labels: enhancement

#57 Add PostgreSQL badge in the README
  README.ko.md
  README.md
Labels: documentation

#59 Commands for one table #58
  README.md
  src/Command/GenerateFactoriesCommand.php
  src/Command/GenerateMigrationsCommand.php
  src/Command/GenerateModelsCommand.php
  src/Command/GenerateSeedersCommand.php
  src/Interfaces/ProviderInterface.php
  src/Laravel/Commands/GenerateFactoriesCommand.php
  src/Laravel/Commands/GenerateMigrationsCommand.php
  src/Laravel/Commands/GenerateModelsCommand.php
  src/Laravel/Commands/GenerateSeedersCommand.php
  src/Provider/MysqlProvider.php
  src/Provider/PgsqlProvider.php
  src/Provider/SqliteProvider.php
  src/Support/Path.php
  src/Table.php
  src/Xeed.php
  tests/Laravel/Commands/GenerateFactoriesCommandTest.php
  tests/Laravel/Commands/GenerateMigrationsCommandTest.php
  tests/Laravel/Commands/GenerateModelsCommandTest.php
  tests/Laravel/Commands/GenerateSeedersCommandTest.php
  tests/Unit/Command/GenerateFactoriesCommandTest.php
  tests/Unit/Command/GenerateMigrationsCommandTest.php
  tests/Unit/Command/GenerateModelsCommandTest.php
  tests/Unit/Command/GenerateSeedersCommandTest.php
  tests/Unit/Generators/DatabaseSeederGeneratorTest.php
  tests/Unit/Generators/ModelGeneratorTest.php
  tests/Unit/Generators/SeederGeneratorTest.php
Labels: enhancement

#60 Fix laravel commads
  src/Laravel/Commands/GenerateDatabaseSeederCommand.php
  src/Laravel/Commands/GenerateFactoriesCommand.php
  src/Laravel/Commands/GenerateMigrationsCommand.php
  src/Laravel/Commands/GenerateModelsCommand.php
  src/Laravel/Commands/GenerateSeedersCommand.php
Labels: bug
